### ISSUE TITLE
Resolve dependencies for Dio v5

### ISSUE THREAD

**Issue by levi956** [devmuaz/awesome_dio_interceptor#3]
The current version of awesome Dio interceptors isn't resolvable with Dio v5.
Please would be nice if a dependency update is made. Thanks.

**Comment by devmuaz** [comment]
Hello @levi956 thanks for opening the issue,
I've updated the package in order to meet the latest changes, now [awesome_dio_interceptor](https://pub.dev/packages/awesome_dio_interceptor) supports Dio `v5.x.x`.

I'm gonna be closing the issue but feel free to reopen it or open new one if you find anything wrong!

And consider supporting me by giving the repo a start ⭐️, it would mean a lot!

**Comment by levi956** [comment]
Thank you.
